name: Terraform PR Checks

on:
  pull_request:
    branches: [ main ]

# Add this to override default write-all permissions
permissions: read-all

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # TODO: should switch from version to commit SHA to increase security

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12 # TODO: should switch from version to commit SHA to increase security
        with:
          directory: .
          quiet: true
